name: haclathon_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - jupyterlab>=4.4.0
  - jupytext
  - jupyterlab-git
  - pip
  - adjusttext
  - bokeh
  - geoviews-core
  - holoviews
  - datashader
  - dask
  - geopandas>=1.0.0
  - hvplot
  - numpy
  - mapclassify
  - python-dotenv
  - rasterio
  - rioxarray
  - seaborn
  - shapely